export const TENTATIVAS = 6;
export const TAMANHO_PALAVRA = 5;

export const XINGOS = [
    "antao", "antas", "azeda", "azedo",
    "babao", "bagos", "bagre", "banal",
    "bebum",
    "besta", "bicha", "bicho", "birra",
    "bisca", "bobao", "bocal", "bocao",
    "bocos", "bosta", "brega", "bruta",
    "bruto", "bruxa", "bunda", "burra",
    "burro", "cagao", "calva", "calvo",
    "carai", "cabra", "chata", "chato", "chula",
    "chulo", "chupa", "corna", "corno",
    "cuzao", "debil", "doida", "doido",
    "droga",
    "falsa", "falso", "feiao", "fodao",
    "fedor", "fraca", "fraco", "froxa",
    "gados", "grelo", "jegue",
    "kenga", "ladra", "lerda", "lerdo",
    "lesmo", "lixao", "lorpa", "manco",
    "meiao",
    "melga", "merda", "mijao", "monga", "mongo",
    "mosca",
    "noias", "nojao", "patao", "peida",
    "palha", "pasmo", "peido", "peste", "picao", "pifia",
    "pifio", "pinto", "pobre", "podre",
    "porca", "porco", "porra", "putao",
    "putos", "raiva", "ranco", "ranho",
    "ronha", "sarna", "senil", "sonsa",
    "sonso", "suina", "suino", "sujas",
    "sujos", "tansa", "tanso", "teima",
    "tanga", "tedio", "tensa", "tenso", "tezao", "tonta",
    "tonto", "torpe", "torta", "torto",
    "tosca", "tosco", "trapo", "troxa",
    "vadia", "vadio", "vazia", "vazio",
    "velha", "velho", "verme", "vesgo",
    "viada", "viado", "vilao", "visgo", "xibiu",
    "xotas", "zonza", "zonzo",
];
