export const TAMANHO_PALAVRA = 5;

export const XINGOS = [
    "antao", "antas", "azeda", "azedo",
    "babao", "bagos", "bagre", "bebum",
    "besta", "bicha", "bicho", "birra",
    "bisca", "bobao", "bocal", "bocao",
    "bocos", "bosta", "brega", "bruta",
    "bruto", "bruxa", "bunda", "burra",
    "burro", "cagao", "calva", "calvo",
    "carai", "chata", "chato", "chula",
    "chulo", "chupa", "corna", "corno",
    "cuzao", "debil", "doida", "doido",
    "falsa", "falso", "feiao", "fodao",
    "fraco", "gados", "grelo", "jegue",
    "kenga", "ladra", "lerda", "lerdo",
    "lesmo", "lixao", "manco", "meiao",
    "merda", "mijao", "monga", "mongo",
    "noias", "nojao", "patao", "peida",
    "peido", "peste", "picao", "pifia",
    "pifio", "pinto", "pobre", "podre",
    "porca", "porco", "porra", "putao",
    "putos", "ranco", "ranho", "sonsa",
    "sonso", "suina", "suino", "sujas",
    "sujos", "tansa", "tanso", "teima",
    "tensa", "tenso", "tezao", "tonta",
    "tonto", "torpe", "torta", "torto",
    "tosca", "tosco", "trapo", "troxa",
    "vadia", "vadio", "vazia", "vazio",
    "verme", "viada", "viado", "xibiu",
    "xotas", "zonza", "zonzo",
];
